<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerXhohh68\appTestDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerXhohh68/appTestDebugProjectContainer.php';
}

if (!class_exists(appTestDebugProjectContainer::class, false)) {
    class_alias(\ContainerXhohh68\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerXhohh68\appTestDebugProjectContainer();
