<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerHkyxa9e\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerHkyxa9e/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerHkyxa9e\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHkyxa9e\appDevDebugProjectContainer();
