<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerBsmd6zm\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerBsmd6zm/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerBsmd6zm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBsmd6zm\appDevDebugProjectContainer();
