<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerPb0gvvp\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerPb0gvvp/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerPb0gvvp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPb0gvvp\appDevDebugProjectContainer();
